source 'https://rubygems.org'
ruby '2.4.3'
gem 'jekyll', '~> 3.4'
gem 'jekyll-assets', '~> 2.2'
gem 'rack-jekyll', '~> 0.5'
gem 'kramdown', '~> 1.13'
gem 'rake'
gem 'sass', '~> 3.4'
gem 'uglifier', '~> 4.1'
gem 'github-pages', '~> 134'
gem 'mini_magick', '~> 4.8'
#gem 'rmagick', '~> 2.16'
gem 'exifr', '~> 1.2'
