source 'https://rubygems.org'
ruby '2.1.7'
gem 'jekyll', '~> 2.4'
gem 'jekyll-assets', '~> 0.14'
gem 'rack-jekyll', '~> 0.3'
gem 'kramdown', '~> 1.5'
gem 'rake'
gem 'sass', '~> 3.4'
gem 'uglifier', '~> 2.7'
gem 'github-pages', '~> 34'
gem 'rmagick', '~> 2.16'
gem 'exifr', '~> 1.2'
