source 'https://rubygems.org'
ruby '2.1.5'
gem 'jekyll', '> 2.0'
gem 'jekyll-assets'
gem 'rack-jekyll'
gem 'kramdown'
gem 'rake'
gem 'sass'
gem 'uglifier'
gem 'github-pages'
gem 'rmagick'
gem 'exifr'
